### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-frontend#1]
- [x] 1. Set up AWS Amplify for frontend web hosting (DevOps)
  - https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html
- [x] 2. Add login page as a public protected route
  - https://medium.com/@thanhbinh.tran93/private-route-public-route-and-restricted-route-with-react-router-d50b27c15f5e
  - https://chakra-ui.com/docs/getting-started
- [x] 3. Use pre-built Amplify UI for Login
  - https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#option-1-use-pre-built-ui-components
  - https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource

**Comment by madanalogy** [comment]
@Linettehtx can you try taking on the first task? Setting up AWS Amplify

**Comment by Linettehtx** [comment]
Can, I can look into that!

**Comment by Linettehtx** [comment]
Should I move on to the next task?

**Comment by madanalogy** [comment]
> Should I move on to the next task?

Can get started now that the backend is up and running. You probably need the cognito client name & ID.
- App Client Name: [cep-dev-pool-client](https://ap-southeast-1.console.aws.amazon.com/cognito/v2/idp/user-pools/ap-southeast-1_jQvny7Obj/app-integration/clients/4di3ok0u52ari4i20om9icj421?region=ap-southeast-1)
- App Client ID: `4di3ok0u52ari4i20om9icj421`
- Cognito User Pool ID: `ap-southeast-1_jQvny7Obj`

**Comment by madanalogy** [comment]
All tasks done, UI migrated to [AmplifyUI](https://ui.docs.amplify.aws/components?platform=react)
