### ISSUE TITLE
Alpha Release Checklist

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-frontend#2]
- [x] Continuous deployment of static site to public S3 #1 
- [x] Login flow using AWS Cognito via AWS Amplify #1 
- [x] Simple user dashboard #3 
- [x] Interaction with backend services for features #3

**Comment by madanalogy** [comment]
API Endpoint URL: `https://4j79c0q05e.execute-api.ap-southeast-1.amazonaws.com/Prod/`
